Python problems
Issues with python path fixed

diff --git a/modules/General/bcftools b/modules/General/bcftools
--- a/modules/General/bcftools
+++ b/modules/General/bcftools
@@ -102,6 +102,11 @@ Noah Gettle 2016"
 		make
 		cp $DOWNLOAD_DIR/bcftools-1.3.1/bcftools $DOWNLOAD_DIR/bcftools-1.3.1/plot-vcfstats $DOWNLOAD_DIR/bcftools-1.3.1/vcfutils.pl $INSTALL_DIR/bin/
 		rm $DOWNLOAD_DIR/bcftools-1.3.1.tar.bz2
+		if ! type "bcftools" >/dev/null 2>/dev/null 
+		then
+			echo "MONGER INSTALL ERROR: Something went wrong when installing BCFTOOLS. Sorry, but you may need to try manual installation."
+			exit 1
+		fi
 	else
 		echo "> MONGER INSTALL: $MODULE_NAME already installed. Skipping..."
 	fi
diff --git a/modules/General/gatk b/modules/General/gatk
--- a/modules/General/gatk
+++ b/modules/General/gatk
@@ -125,6 +125,11 @@ $AUTHOR_INFO"
 			sed -i "s|alias gatk=.*|$newline|" ~/.bashrc
 		fi
 		. ~/.bashrc
+		if ! type "gatk" >/dev/null 2>/dev/null 
+		then
+			echo "MONGER INSTALL ERROR: Something went wrong when installing GATK. Sorry, but you may need to try manual installation."
+			exit 1
+		fi
 		##############################
 	else
 		echo "> MONGER INSTALL: $MODULE_NAME already installed. Skipping..."
diff --git a/modules/General/htseq b/modules/General/htseq
--- a/modules/General/htseq
+++ b/modules/General/htseq
@@ -117,6 +117,11 @@ $AUTHOR_INFO"
 	then
 		echo -e "> MONGER INSTALL: Installing $MODULE_NAME."
 		pip install HTSeq
+		if ! type "htseq-count" >/dev/null 2>/dev/null 
+		then
+			echo "MONGER INSTALL ERROR: Something went wrong when installing HTSEQ. Sorry, but you may need to try manual installation."
+			exit 1
+		fi
 	else
 		echo "> MONGER INSTALL: $MODULE_NAME already installed. Skipping..."
 	fi
diff --git a/modules/General/parallel b/modules/General/parallel
--- a/modules/General/parallel
+++ b/modules/General/parallel
@@ -95,11 +95,17 @@ Noah Gettle 2016"
 		then
 			wget ftp://ftp.gnu.org/gnu/parallel/parallel-latest.tar.bz2
 		fi
+		rm -rf $DOWNLOAD_DIR/parallel-20*
 		tar -xjvf $DOWNLOAD_DIR/parallel-latest.tar.bz2
 		cd $DOWNLOAD_DIR/parallel-20*
 		./configure --prefix $INSTALL_DIR && make && make install
 		parallel --citation
 		rm -rf $DOWNLOAD_DIR/parallel-latest.tar.bz2
+		if ! type "parallel" >/dev/null 2>/dev/null 
+		then
+			echo "MONGER INSTALL ERROR: Something went wrong when installing PARALLEL. Sorry, but you may need to try manual installation."
+			exit 1
+		fi
 	else
 		echo "> MONGER INSTALL: $MODULE_NAME already installed. Skipping..."
 	fi
diff --git a/modules/General/perl5 b/modules/General/perl5
--- a/modules/General/perl5
+++ b/modules/General/perl5
@@ -102,6 +102,11 @@ Noah Gettle 2016"
 		set -e
 		make install
 		rm $DOWNLOAD_DIR/perl-5.24.0.tar.gz
+		if ! type "perl" >/dev/null 2>/dev/null 
+		then
+			echo "MONGER INSTALL ERROR: Something went wrong when installing PERL. Sorry, but you may need to try manual installation."
+			exit 1
+		fi
 	else
 		echo "> MONGER INSTALL: $MODULE_NAME already installed. Skipping..."
 		mkdir -p $INSTALL_DIR/lib/perl5
diff --git a/modules/General/picard b/modules/General/picard
--- a/modules/General/picard
+++ b/modules/General/picard
@@ -103,6 +103,11 @@ Noah Gettle 2016"
 			sed -i "s|alias picard=.*|$newline|" ~/.bashrc
 		fi
 		. ~/.bashrc
+		if ! type "picard.jar" >/dev/null 2>/dev/null 
+		then
+			echo "MONGER INSTALL ERROR: Something went wrong when installing PICARD. Sorry, but you may need to try manual installation."
+			exit 1
+		fi
 	else
 		echo "> MONGER INSTALL: $MODULE_NAME already installed. Skipping..."
 	fi
diff --git a/modules/General/python3 b/modules/General/python3
--- a/modules/General/python3
+++ b/modules/General/python3
@@ -95,6 +95,24 @@ $AUTHOR_INFO"
 	####### INSTALL DEPENDENCIES #######
 	####################################
 
+	# ##########
+	# # LIBBZ2 #
+	# ##########
+	# libbz2afile=`find $LD_LIBRARY_PATH_SEP -maxdepth 1 -name 'libbz2.a' | head -1`
+	# if [ "$libbz2afile" == "" ]
+	# then
+	# 	echo -e "> MONGER INSTALL: Installing LIBBZ2."
+	# 	cd $DOWNLOAD_DIR
+	# 	if ! test -f $DOWNLOAD_DIR/bzip2-1.0.6.tar.gz
+	# 	then
+	# 		wget http://www.bzip.org/1.0.6/bzip2-1.0.6.tar.gz
+	# 	fi
+	# 	tar -zxvf $DOWNLOAD_DIR/bzip2-1.0.6.tar.gz
+	# 	cd $DOWNLOAD_DIR/bzip2-1.0.6
+	# 	make
+	# 	make install PREFIX=$INSTALL_DIR
+	# fi
+	#
 	###############################################
 
 	####################################
@@ -117,21 +135,36 @@ $AUTHOR_INFO"
 		./configure --prefix=$INSTALL_DIR
 		make
 		make install
-		rm -rf $DOWNLOAD_DIR/Python-3.5.2.tgz
-		if `grep -q "export PYTHONPATH=" ~/.bashrc`
+		if ! type "python3" >/dev/null 2>/dev/null 
 		then
-			sed -i "s|export PYTHONPATH=.*|export PYTHONPATH=$INSTALL_DIR/lib/python3.5\:$PYTHONPATH|" ~/.bashrc
-		else
-			echo "export PYTHONPATH=$INSTALL_DIR/lib/python3.5:$PYTHONPATH" >> ~/.bashrc
+			echo "MONGER INSTALL ERROR: Something went wrong when installing PYTHON3. Sorry, but you may need to try manual installation."
+			exit 1
 		fi
+		rm -rf $DOWNLOAD_DIR/Python-3.5.2.tgz
+		pythondir=$INSTALL_DIR/lib/python3.5
+	else
+		pythondir=`which python3`
+		pythondir=`dirname $pythondir`
+		pythondir=`dirname $pythondir`
+		pythondir=$pythondir/lib/python3.*
+		echo "> MONGER INSTALL: $MODULE_NAME already installed. Skipping..."
+	fi
 	else
 		echo "> MONGER INSTALL: $MODULE_NAME already installed. Skipping..."
 	fi
-	
+	if `grep -q "export PYTHONPATH=" ~/.bashrc`
+	then
+		if `grep -q "export PYTHONPATH=*$pythondir*" ~/.bashrc`
+		then
+			sed -i "s|export PYTHONPATH=.*|export PYTHONPATH=$pythondir\:$PYTHONPATH|" ~/.bashrc
+		fi
+	else
+		echo "export PYTHONPATH=$pythondir:$PYTHONPATH" >> ~/.bashrc
+	fi
 	#######
 	# PIP #
 	#######
-	pythondir=`which python2`
+	pythondir=`which python3`
 	pythondir=`dirname $pythondir`
 	pythondir=`dirname $pythondir`
 	export PYTHONPATH=$pythondir/lib/python3.*
@@ -139,10 +172,16 @@ $AUTHOR_INFO"
 	then
 		echo -e "> MONGER INSTALL: Installing $MODULE_NAME PIP."
 		cd $DOWNLOAD_DIR
-		rm -rf $DOWNLOAD_DIR/get-pip.py
+		rm -rf $DOWNLOAD_DIR/get-pip.py*
 		wget https://bootstrap.pypa.io/get-pip.py
 		rm -rf $pythondir/lib/python3.*/site-packages/pip*
-		python3 get-pip.py --prefix $INSTALL_DIR
+		python3 $DOWNLOAD_DIR/get-pip.py --prefix $INSTALL_DIR
+		if ! type "pip3" >/dev/null 2>/dev/null 
+		then
+			echo "MONGER INSTALL ERROR: Something went wrong when installing PIP3. Sorry, but you may need to try manual installation."
+			exit 1
+		fi
+		pip3 install --upgrade setuptools
 	else
 		echo "> MONGER INSTALL: $MODULE_NAME PIP already installed. Skipping..."
 	fi
